Repository react-hookz/web, pull requests merged in 2021-04, with the labels that each got.

#1 docs: update useMountEffect and useUpdateEffect docs
  src/useMountEffect.ts
  src/useUpdateEffect.ts
Labels: documentation

#2 fix: dist package returned to bundle
  .github/workflows/ci-cd.yml
  package.json
Labels: bug fix

#3 feat: useToggle hook
  .eslintrc.js
  src/index.ts
  src/useToggle.ts
  src/util/resolveHookState.ts
  tests/dom/useToggle.ts
  tests/dom/util/resolveHookState.ts
  tests/ssr/useToggle.ts
  tsconfig.json
Labels: new hook

#4 Use rerender
  .eslintrc.js
  jest.config.js
  src/index.ts
  src/useFirstMountState.ts
  src/useMountEffect.ts
  src/useRerender.ts
  src/useToggle.ts
  src/useUnmountEffect.ts
  src/useUpdateEffect.ts
  src/util/const.ts
  tests/dom/useRerender.test.ts
  tests/dom/useToggle.test.ts
  tests/dom/util/resolveHookState.test.ts
  tests/ssr/useRerender.test.ts
  tests/ssr/useToggle.test.ts
Labels: new hook

#14 docs: suggested language changes to README
  CHANGELOG.md
  README.md
Labels: documentation

#16 docs: introduce CONTRIBUTING.md
  .editorconfig
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation

#25 feat: new hook usePrevious
  README.md
  src/index.ts
  src/usePrevious.ts
  stories/usePrevious.stories.tsx
  stories/usePrevious.story.mdx
  tests/dom/usePrevious.test.ts
  tests/ssr/usePrevious.test.ts
Labels: new hook

#24 feat: new hook useIsMounted
  README.md
  src/index.ts
  src/useIsMounted.ts
  stories/useIsMounted.stories.tsx
  stories/useIsMounted.story.mdx
  tests/dom/useIsMounted.test.ts
  tests/ssr/useIsMounted.test.ts
Labels: new hook

#27 fix: default useUnmountEffect example to false
  stories/useUnmountEffect.stories.tsx
Labels: documentation

#26 feat: new hooks, useConditionalEffect and useConditionalUpdateEffect
  README.md
  src/index.ts
  src/useConditionalEffect.ts
  src/useConditionalUpdateEffect.ts
  src/useUpdateEffect.ts
  src/util/const.ts
  stories/useConditionalEffect.stories.tsx
  stories/useConditionalEffect.story.mdx
  stories/useConditionalUpdateEffect.stories.tsx
  stories/useConditionalUpdateEffect.story.mdx
  stories/useIsMounted.stories.tsx
  stories/useUnmountEffect.stories.tsx
  tests/dom/useConditionalEffect.test.ts
  tests/dom/useConditionalUpdateEffect.test.ts
  tests/ssr/useConditionalEffect.test.ts
  tests/ssr/useConditionalUpdateEffect.test.ts
Labels: new hook
