Repository react-hookz/web, pull requests merged in 2021-05, with the labels that each got.

#32 feat: new hook useMediatedState
  README.md
  package.json
  src/index.ts
  src/useMediatedState.ts
  stories/useMediatedState.stories.tsx
  stories/useMediatedState.story.mdx
  tests/dom/useMediatedState.test.ts
  tests/ssr/useMediatedState.test.ts
  yarn.lock
Labels: new hook

#34 docs: alphabetize hooks README like storybook
  README.md
Labels: documentation

#35 feat: new hook, useNetworkState
  CONTRIBUTING.md
  README.md
  src/useNetworkState.ts
  src/util/misc.ts
  stories/useMediatedState.story.mdx
  stories/useNetworkState.stories.tsx
  stories/useNetworkState.story.mdx
  tests/dom/useNetworkState.test.ts
  tests/dom/util/misc.test.ts
  tests/ssr/useNetworkState.test.ts
Labels: new hook

#41 feat: new hook `useIsomorphicLayoutEffect`
  README.md
  src/index.ts
  src/useIsomorphicLayoutEffect.ts
  stories/useIsomorphicLayoutEffect.story.mdx
  tests/dom/useIsomorphicLayoutEffect.test.ts
  tests/ssr/useIsomorphicLayoutEffect.test.ts
Labels: new hook

#40 feat: new hook `useDebounceCallback`
  README.md
  src/index.ts
  src/useDebounceCallback.ts
  stories/Callback/useDebounceCallback.stories.tsx
  stories/Callback/useDebounceCallback.story.mdx
  stories/Lifecycle/useIsomorphicLayoutEffect.story.mdx
  tests/dom/useDebounceCallback.test.ts
  tests/ssr/useDebounceCallback.test.ts
Labels: new hook

#42 feat: new hook `useSyncedRef`
  README.md
  src/index.ts
  src/useMediatedState.ts
  src/useSyncedRef.ts
  stories/Miscellaneous/useSyncedRef.stories.tsx
  stories/Miscellaneous/useSyncedRef.story.mdx
  tests/dom/useSyncedRef.test.ts
  tests/ssr/useSyncedRef.test.ts
Labels: new hook

#43 feat: new hooks `useLocalStorageValue` and `useSessionStorageValue`
  .storybook/preview.js
  README.md
  src/index.ts
  src/useLocalStorageValue.ts
  src/useSessionStorageValue.ts
  src/useStorageValue.ts
  src/util/const.ts
  stories/Lifecycle/useIsMounted.story.mdx
  stories/Lifecycle/useRerender.story.mdx
  stories/SideEffects/useLocalStorageValue.stories.tsx
  stories/SideEffects/useLocalStorageValue.story.mdx
  stories/SideEffects/useSessionStorageValue.stories.tsx
  stories/SideEffects/useSessionStorageValue.story.mdx
  stories/State/useMediatedState.story.mdx
  stories/State/useSafeState.story.mdx
  stories/State/useToggle.story.mdx
  tests/dom/useLocalStorageValue.test.ts
  tests/dom/useSessionStorageValue.test.ts
  tests/dom/useStorageValue.test.ts
  tests/ssr/useLocalStorageValue.test.ts
  tests/ssr/useSessionStorageValue.test.ts
  tests/ssr/useStorageValue.test.ts
  tsconfig.json
  yarn.lock
Labels: new hook

#66 feat: new hook `useRafCallback`
  .eslintrc.js
  README.md
  src/index.ts
  src/useRafCallback.ts
  stories/Callback/useRafCallback.stories.tsx
  stories/Callback/useRafCallback.story.mdx
  stories/State/useMediatedState.story.mdx
  stories/State/useSafeState.story.mdx
  stories/State/useToggle.story.mdx
  tests/dom/useNetworkState.test.ts
  tests/dom/useRafCallback.test.ts
  tests/ssr/useNetworkState.test.ts
  tests/ssr/useRafCallback.test.ts
Labels: new hook

#76 Fix tests
  package.json
  src/index.ts
  src/useDebounceCallback.ts
  src/useLocalStorageValue.ts
  src/useMediatedState.ts
  src/useResizeObserver.ts
  src/useSessionStorageValue.ts
  stories/Callback/useDebounceCallback.story.mdx
  stories/Lifecycle/useIsomorphicLayoutEffect.story.mdx
  stories/Miscellaneous/useSyncedRef.story.mdx
  stories/SideEffect/useLocalStorageValue.stories.tsx
  stories/SideEffect/useLocalStorageValue.story.mdx
  stories/SideEffect/useSessionStorageValue.stories.tsx
  stories/SideEffect/useSessionStorageValue.story.mdx
  tests/dom/useConditionalEffect.test.ts
  tests/dom/useConditionalUpdateEffect.test.ts
  tests/dom/useDebounceCallback.test.ts
  tests/dom/useLocalStorageValue.test.ts
  tests/dom/useMediatedState.test.ts
  tests/dom/useNetworkState.test.ts
  tests/dom/usePrevious.test.ts
  tests/dom/useSessionStorageValue.test.ts
  tests/dom/useStorageValue.test.ts
  tests/dom/useSyncedRef.test.ts
  tests/dom/util/misc.test.ts
  tests/ssr/useConditionalEffect.test.ts
  tests/ssr/useConditionalUpdateEffect.test.ts
  tests/ssr/useDebounceCallback.test.ts
  tests/ssr/useLocalStorageValue.test.ts
  tests/ssr/useMediatedState.test.ts
  tests/ssr/useNetworkState.test.ts
  tests/ssr/usePrevious.test.ts
  tests/ssr/useSessionStorageValue.test.ts
  tests/ssr/useStorageValue.test.ts
  tests/ssr/useSyncedRef.test.ts
  tsconfig.json
  yarn.lock
Labels: bug fix

#77 feat: add discord release notify action
  .github/workflows/discord-release-notify.yml
Labels: enhancement, github_actions

#67 feat: new hook `useResizeObserver`
  README.md
  src/index.ts
  src/useResizeObserver.ts
  stories/Sensor/useResizeObserver.stories.tsx
  stories/Sensor/useResizeObserver.story.mdx
  tests/dom/useResizeObserver.test.ts
  tests/ssr/useResizeObserver.test.ts
Labels: new hook

#80 feat: new hook `useMeasure`
  README.md
  src/useMeasure.ts
  stories/Sensor/useMeasure.stories.tsx
  stories/Sensor/useMeasure.story.mdx
  stories/Sensor/useResizeObserver.stories.tsx
  tests/dom/useMeasure.test.ts
  tests/ssr/useMeasure.test.ts
Labels: new hook

#68 feat: new hook `useTitle`
  src/index.ts
  src/useTitle.ts
  stories/Dom/useTitle.stories.tsx
  stories/Dom/useTitle.story.mdx
  tests/dom/useTitle.test.ts
  tests/ssr/useTitle.test.ts
Labels: new hook
